server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-route
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: hotel-mgt-route
          uri: lb://hotel-mgt-service
          predicates:
            - Path=/api/inventory/**
        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: reservation-route
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG